Revert "framework: call _get_all_alerts_since() with str(since)"
This reverts commit 7a713182496491d9fe9b6e63f32995b65a36f2fd.

Fixes:

 Error org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib64/python2.7/site-packages/setroubleshoot/server.py", line 504, in get_all_alerts_since
    return self._get_all_alerts_since(str(since), sender)
  File "/usr/lib64/python2.7/site-packages/setroubleshoot/server.py", line 492, in _get_all_alerts_since
    since_alerts = setroubleshoot.util.TimeStamp(float(since / 1000000))
TypeError: unsupported operand type(s) for /: 'str' and 'int'