framework: Handla all exceptions from do_analyze_logfile()
Fixes:
$ sudo umount /sys/fs/selinux

$ sudo sealert -a /var/log/audit/audit.log
Opps, sealert hit an error!

ValueError: You must specify the -p option with the path to the policy file.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/sealert", line 695, in <module>
    do_analyze_logfile(logfile)
  File "/usr/bin/sealert", line 532, in do_analyze_logfile
    audit2why.init()
SystemError: <built-in function init> returned a result with an error set