framework: Catch all subprocess exceptions
Some exceptions were not correctly handled so that setroubleshootd could
stop work, e.g., in a case where there's no 'locate' in the system

Fixes regression brought by e69378d7:

  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory