framwork: Fix get_all_alerts_ignored()
Fixes:
 Error org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File /usr/lib64/python2.7/site-packages/dbus/service.py, line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File /usr/lib64/python2.7/site-packages/setroubleshoot/server.py, line 528, in get_all_alerts_ignored
    return self._get_all_alerts_since('1970-01-01T00:00:00Z', sender, alert_action=ignore)
  File /usr/lib64/python2.7/site-packages/setroubleshoot/server.py, line 492, in _get_all_alerts_since
    since_alerts = setroubleshoot.util.TimeStamp(float(since / 1000000))
TypeError: unsupported operand type(s) for /: 'str' and 'int' Error org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):