framework: sepolicy.info() returns a generator, not a list
Commit c55edb36ca68 ("framework: Fix AVC.__typeMatch to handle aliases
properly") was forward ported from stable branch. Unfortunately, stable branch
is supposed to be used with sepolicy version which generates a list, while
master branch is used with version generating a generator.

Fixes:
  File "/usr/lib/python3.8/site-packages/setroubleshoot/audit_data.py", line 737, in __typeMatch
    _info = info(TYPE, context.type)[0]
  TypeError: 'generator' object is not subscriptable

Resolves:  https://bugzilla.redhat.com/show_bug.cgi?id=1784564