framework: call _get_all_alerts_since() with str(since)
Fixes:
dbus-send --system --print-reply --dest=org.fedoraproject.Setroubleshootd /org/fedoraproject/Setroubleshootd org.fedoraproject.SetroubleshootdIface.get_all_alerts_since string:'2015-10-19T00:00:00Z'
Error org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib64/python2.7/site-packages/setroubleshoot/server.py", line 503, in get_all_alerts_since
    return self._get_all_alerts_since(since, sender)
  File "/usr/lib64/python2.7/site-packages/setroubleshoot/server.py", line 491, in _get_all_alerts_since
    since_alerts = setroubleshoot.util.TimeStamp(since)
  File "/usr/lib64/python2.7/site-packages/setroubleshoot/util.py", line 643, in __init__
    raise TypeError("must be string, float, datetime, or TimeStamp")
TypeError: must be string, float, datetime, or TimeStamp