sort() function expects keyword arguments
Fixes:
Error org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/dbus/service.py", line 826, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.4/site-packages/setroubleshoot/server.py", line 462, in check_for_new
    signatures.sort(compare_sig)
TypeError: must use keyword argument for key function